name: complex-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.0
  - pandas=1.3.0
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - requests==2.25.1
    - flask 